/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package serialj;

import javax.swing.SwingUtilities;

/**
 *
 * @author Libra
 */
public class FrmHuman extends javax.swing.JFrame {

    private PortAccessor p;

    /**
     * Creates new form FrmHuman
     */
    public FrmHuman() {
        initComponents();
        jPanel7.remove(jButton4);
        jPanel7.remove(jButton5);
        jPanel7.remove(jButton6);
        jPanel7.remove(jButton7);
        jPanel7.remove(jButton8);
        jPanel7.remove(jButton9);
        jPanel3.remove(btn2);
        jPanel3.remove(btn3);
        jPanel3.remove(btn5);
        jPanel3.remove(btn6);
    }

    public void setPort(PortAccessor p) {
        this.p = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnTaskType = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblHumanTips = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        rdoSort = new javax.swing.JRadioButton();
        rdoMatch = new javax.swing.JRadioButton();
        rdoCapacity = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnMatch = new javax.swing.JButton();
        btnNonMatch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("嗅觉认知测试");
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        lblHumanTips.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        lblHumanTips.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHumanTips.setText("嗅觉认知测试");
        lblHumanTips.setAlignmentX(0.5F);
        jPanel4.add(lblHumanTips);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel5.setLayout(new java.awt.GridLayout(3, 1));

        btnTaskType.add(rdoSort);
        rdoSort.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        rdoSort.setSelected(true);
        rdoSort.setText("排序");
        rdoSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoSortActionPerformed(evt);
            }
        });
        jPanel5.add(rdoSort);

        btnTaskType.add(rdoMatch);
        rdoMatch.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        rdoMatch.setText("比较");
        rdoMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMatchActionPerformed(evt);
            }
        });
        jPanel5.add(rdoMatch);

        btnTaskType.add(rdoCapacity);
        rdoCapacity.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        rdoCapacity.setText("容量");
        rdoCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoCapacityActionPerformed(evt);
            }
        });
        jPanel5.add(rdoCapacity);

        jPanel1.add(jPanel5, java.awt.BorderLayout.EAST);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        btn1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        btn1.setText("<html>全部是<br>甲气味</html>");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel3.add(btn1);

        btn2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        btn2.setText("<html>甲气味<br>5/6</html>");
        btn2.setEnabled(false);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel3.add(btn2);

        btn3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        btn3.setText("<html>甲气味<br>4/6</html>");
        btn3.setEnabled(false);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel3.add(btn3);

        btn4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        btn4.setText("各一半");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel3.add(btn4);

        btn5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        btn5.setText("<html>乙气味<br>4/6</html>");
        btn5.setEnabled(false);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel3.add(btn5);

        btn6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        btn6.setText("<html>乙气味<br>5/6</html>");
        btn6.setEnabled(false);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel3.add(btn6);

        btn7.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        btn7.setText("<html>全部是<br>乙气味</html>");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel3.add(btn7);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(jPanel3, gridBagConstraints);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new java.awt.GridLayout(2, 1));

        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("1（不确定，猜的）<<<-------------------------->>>3（确定正确）");
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel8.add(jLabel1);

        jPanel6.add(jPanel8);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1);

        jButton2.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2);

        jButton3.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton3);

        jButton4.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jButton4.setText("4");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4);

        jButton5.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jButton5.setText("5");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton5);

        jButton6.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jButton6.setText("6");
        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton6);

        jButton7.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jButton7.setText("7");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton7);

        jButton8.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jButton8.setText("8");
        jButton8.setEnabled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton8);

        jButton9.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jButton9.setText("9");
        jButton9.setEnabled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton9);

        jPanel6.add(jPanel7);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(jPanel6, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 6, 0));

        btnMatch.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        btnMatch.setText("相同");
        btnMatch.setEnabled(false);
        btnMatch.setMaximumSize(new java.awt.Dimension(32767, 32767));
        btnMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatchActionPerformed(evt);
            }
        });
        jPanel2.add(btnMatch);

        btnNonMatch.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        btnNonMatch.setText("不同");
        btnNonMatch.setEnabled(false);
        btnNonMatch.setMaximumSize(new java.awt.Dimension(32767, 32767));
        btnNonMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNonMatchActionPerformed(evt);
            }
        });
        jPanel2.add(btnNonMatch);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatchActionPerformed
        p.writeByte((byte) 0x31);
    }//GEN-LAST:event_btnMatchActionPerformed

    private void btnNonMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNonMatchActionPerformed
        p.writeByte((byte) 0x32);
    }//GEN-LAST:event_btnNonMatchActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        p.writeByte((byte) 0x33);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        p.writeByte((byte) 0x31);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        p.writeByte((byte) 0x32);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        p.writeByte((byte) 0x32);
//        p.writeByte((byte) 0x34);

    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        p.writeByte((byte) 0x35);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        p.writeByte((byte) 0x36);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
//        p.writeByte((byte) 0x37);
        p.writeByte((byte) 0x33);
    }//GEN-LAST:event_btn7ActionPerformed

    private void rdoMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMatchActionPerformed
        SwingUtilities.invokeLater(() -> {
            if (rdoMatch.isSelected()) {
                btnMatch.setEnabled(true);
                btnNonMatch.setEnabled(true);
                btn1.setEnabled(false);
                btn2.setEnabled(false);
                btn3.setEnabled(false);
                btn4.setEnabled(false);
                btn5.setEnabled(false);
                btn6.setEnabled(false);
                btn7.setEnabled(false);
                btnMatch.setText("相同");
                btnNonMatch.setText("不同");
                jPanel2.revalidate();
                jPanel2.repaint();
            }
        }
        );
    }//GEN-LAST:event_rdoMatchActionPerformed

    private void rdoSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoSortActionPerformed
        SwingUtilities.invokeLater(() -> {
            if (rdoSort.isSelected()) {
                btnMatch.setEnabled(false);
                btnNonMatch.setEnabled(false);
                btn1.setEnabled(true);
//                btn2.setEnabled(true);
//                btn3.setEnabled(true);
                btn4.setEnabled(true);
//                btn5.setEnabled(true);
//                btn6.setEnabled(true);
                btn7.setEnabled(true);
            }
        }
        );
    }//GEN-LAST:event_rdoSortActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        p.writeByte((byte) 0x31);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        p.writeByte((byte) 0x32);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        p.writeByte((byte) 0x33);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        p.writeByte((byte) 0x34);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        p.writeByte((byte) 0x35);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        p.writeByte((byte) 0x36);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        p.writeByte((byte) 0x37);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        p.writeByte((byte) 0x38);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        p.writeByte((byte) 0x39);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void rdoCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoCapacityActionPerformed
        SwingUtilities.invokeLater(() -> {
            if (rdoCapacity.isSelected()) {
                btnMatch.setEnabled(true);
                btnNonMatch.setEnabled(true);
                btn1.setEnabled(false);
                btn2.setEnabled(false);
                btn3.setEnabled(false);
                btn4.setEnabled(false);
                btn5.setEnabled(false);
                btn6.setEnabled(false);
                btn7.setEnabled(false);
                btnMatch.setText("出现过");
                btnNonMatch.setText("没出现过");
                jPanel2.revalidate();
                jPanel2.repaint();
            }
        });
    }//GEN-LAST:event_rdoCapacityActionPerformed

    public void updateTipTxt(String str1, String str2) {
        SwingUtilities.invokeLater(() -> {
            if (str1.contains("testStart")) {
                lblHumanTips.setText("该气味是否出现过？");
            } else if (str1.startsWith("testEnd")) {
                lblHumanTips.setText("请注意气味信号");
            } else if (str1.startsWith("1 for match")) {
                lblHumanTips.setText("气味一和气味二相同吗？");
            } else if (str1.startsWith("Sample")) {
                lblHumanTips.setText("气味一");
            } else if (str1.startsWith("Delay")) {
                lblHumanTips.setText("请保持记忆");
            } else if (str1.startsWith("Test")) {
                lblHumanTips.setText("气味二");
            } else if (str1.startsWith("Correct")) {
                lblHumanTips.setText("正确");
            } else if (str1.startsWith("Incorrect")) {
                lblHumanTips.setText("有偏差");
            } else if (str1.startsWith("Missed")) {
                lblHumanTips.setText("没有回答");
            } else if (str1.startsWith("Gradient")) {
                switch (str2.trim()) {

                    case "0":
                        lblHumanTips.setText("请辨别气味");
                        break;
                    case "1":
                        lblHumanTips.setText("全部是甲气味");
                        break;
                    case "2":
//                        lblHumanTips.setText("甲气味 5/6");
                        lblHumanTips.setText("甲乙各一半");
                        break;
                    case "3":
//                        lblHumanTips.setText("甲气味 4/6");
                        lblHumanTips.setText("全部是乙气味");
                        break;
                    case "4":
                        lblHumanTips.setText("甲乙各一半");
                        break;
                    case "5":
                        lblHumanTips.setText("乙气味 4/6");
                        break;
                    case "6":
                        lblHumanTips.setText("乙气味 5/6");
                        break;
                    case "7":
                        lblHumanTips.setText("全部是乙气味");
                        break;
                }

            } else if (str1.startsWith("Pls_Wait")) {
                lblHumanTips.setText("请辨别气味并保持记忆");
            } else if (str1.startsWith("Pls_Choose")) {
                lblHumanTips.setText("请选择气味");
            } else if (str1.startsWith("Confidence")) {
                lblHumanTips.setText("请选择答案确定程度");
            } else if (str1.startsWith("OdorPrime")) {
                lblHumanTips.setText("气味即将出现");
            }
        });
    }

//    private void updateLblText(String str) {
//        SwingUtilities.invokeLater(() -> {
//            lblHumanTips.setText(str);
//        });
//    }
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmHuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmHuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmHuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmHuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmHuman().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btnMatch;
    private javax.swing.JButton btnNonMatch;
    private javax.swing.ButtonGroup btnTaskType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblHumanTips;
    private javax.swing.JRadioButton rdoCapacity;
    private javax.swing.JRadioButton rdoMatch;
    private javax.swing.JRadioButton rdoSort;
    // End of variables declaration//GEN-END:variables
}
